In [1]:
import numpy as np
import gym
import random

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [4]:
qtable = np.zeros((state_size,action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
total_episodes = 20000
learning_rate = 0.7
max_steps = 99
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [6]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma*np.max(qtable[new_state, :]) - qtable[state,action])
        
        total_rewards += reward
        
        state = new_state
        
        if done == True:
            break
            
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
    
print("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.49945
[[1.65594064e-01 4.88324357e-02 4.72519594e-02 4.93301264e-02]
 [1.73933017e-02 1.69790271e-02 1.28121392e-02 1.58599017e-01]
 [1.42225480e-02 2.72230366e-03 2.04781649e-02 4.02628821e-02]
 [1.12047834e-02 9.39859517e-03 8.90951400e-04 2.51931760e-02]
 [1.67775600e-01 1.71821794e-02 4.22524345e-02 1.13913534e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.06223241e-02 3.71402756e-05 2.46687017e-03 1.26731958e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.24523404e-02 5.68304489e-03 2.90936267e-02 1.42795490e-01]
 [1.65075423e-02 3.58662594e-01 2.59422089e-02 2.70443977e-02]
 [7.40467499e-01 1.88627414e-02 3.25463581e-02 2.62567188e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.24633733e-02 7.67453993e-02 4.83836923e-01 7.71529811e-02]
 [3.40260489e-01 8.63960601e-01 2.63917035e-01 4.03332744e-01]
 [0.00000000e+00 0.00000000e+0

In [7]:
env.reset()

for episode in range(15):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            env.render()
            if new_state == 15:
                print("We reached our Goal 🏆")
            else:
                print("We fell into a hole ☠️")
                
            print("Number of steps", step)
            
            break
        
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 41
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 63
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 25
****************************************************
EPISODE  3
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 57
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 25
****************************************************
EPISODE  5
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 77
****************************************************
EPISODE  6
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 30
****************************************************
EPISO